<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
<style>
  .markdownContent h1{
    font-size:26px;
    font-weight: bold;
    text-align: left;
    margin:0 0 20px;
    padding:0;
  }
  .markdownContent h2{
    font-size:22px;
    font-weight: bold;
    text-align: left;
    margin:30px 0 10px;
    padding:0;
    color:#444;
    background-color: transparent;
  }
  .markdownContent h3{
    font-size:18px;
    font-weight: bold;
    text-align: left;
    margin:10px 0 5px;
    padding:0;
  }
  .markdownContent p{
    font-size: 14px;
  }
</style>
<div id="markdownContent" class="markdownContent"></div>
<?php if (!isset($exclude_chatgpt)):  ?> <p class="chatgpt-markdown"><span class="logo"><img src="/images/logos/chatgpt.png"/></span>Markdown generated by ChatGPT</p> <?php endif; ?>
<script>
  // Fetch the Markdown content
  fetch('README.md')
    .then(function(response) {
      return response.text();
    })
    .then(function(markdown) {
      // Convert Markdown to HTML using marked.js
      var html = marked.parse(markdown);

      // Inject HTML into the div
      document.getElementById('markdownContent').innerHTML = html;
    })
    .catch(function(error) {
      console.error('Error fetching Markdown:', error);
    });
</script>